# Generated by Django 3.0.5 on 2020-04-15 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-joined'], 'permissions': [('c_e_o', 'Chief Executive Officer'), ('director', 'Director'), ('user_support', 'User Management'), ('forum_admin', 'Forum Administrator'), ('promoter', 'Promoter'), ('profile_user', 'Profile User')]},
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_noti', models.BooleanField(default=False)),
                ('sms_noti', models.BooleanField(default=False)),
                ('email_noti', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
