# Generated by Django 3.0.5 on 2020-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200414_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_noti',
            field=models.BooleanField(default=True, verbose_name='Email Notification'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='push_noti',
            field=models.BooleanField(default=False, verbose_name='Push Notification'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sms_noti',
            field=models.BooleanField(default=False, verbose_name='Sms Notification'),
        ),
    ]
