# Generated by Django 3.0.5 on 2020-04-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200414_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='email_noti',
            new_name='email_notification',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='push_noti',
            new_name='push_notification',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='sms_noti',
            new_name='sms_notification',
        ),
    ]
