# Generated by Django 3.0.5 on 2020-04-14 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='discussant', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='discussion_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('IMG', 'Image'), ('VDO', 'Video'), ('STK', 'Sicker'), ('TXT', 'Text'), ('AUD', 'Audio')], max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=forum.utils.message_video_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=forum.utils.message_image_path)),
                ('sticker', models.ImageField(blank=True, null=True, upload_to=forum.utils.message_sticker_path)),
                ('audio', models.FileField(blank=True, null=True, upload_to=forum.utils.message_audio_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['-timestamp'],
            },
        ),
    ]
